### ISSUE TITLE
Design a home page for Hosts

### ISSUE THREAD

**Issue by c-fuchs** [hackforla/HomeUniteUs#188]
### Overview
Design a homepage for Hosts to see after they've completed the sign in wizard, to track their progress through the matching process. 

### Action Items
- [ ] Review user flow
- [ ] Review host home page design with @abbyhipp to discuss current requirements
   - [ ] Design a home page for hosts to see their current status, completed steps, next steps, and links to any outside resources needed to complete steps

### Resources/Instructions
[Current User Flow WIP](https://www.figma.com/file/BJL6ZHfjrxVhU8jvD9gB3P/HomeUniteUs-Everything-Figma?node-id=51%3A2579)

[Current Host dashboard screen](https://www.figma.com/file/BJL6ZHfjrxVhU8jvD9gB3P/HomeUniteUs-Everything-Figma?node-id=53%3A2615)

**Comment by amimorga** [comment]
Here are a few revised wireframes from last saturday's meeting. I read through the host handbook to get a better understanding of what the user would see and took out the calendar since the other team is working on that
https://www.figma.com/file/iFZz1kx2RqjJgpxdttFluU/Host-Dashboard-Multiple-Views?node-id=22%3A2
