### ISSUE TITLE
Design state management infrastructure and specify standard protocols for data access

### ISSUE THREAD

**Issue by tylerthome** [hackforla/HomeUniteUs#194]
### Overview
We need a front end architecture so that data access and state management are standardized for UI components in order to ensure consistency of developer production.

### Action Items
Using the React Context API and and internal component state management semantics, design a standard approach for generic component trees to access data and manage internal state

- [ ] Specify what classes of data and operations will be exposed from the context level. This may include hierarchical relationships, as well as global and local application state
- [ ] Create diagrams depicting a generic architecture, including components and contexts, which adhere to this protocol

- [ ] Release dependency on #173 and #193  for this issue (mark it in top section under actions.  If both are released, move that issue to prioritized backlog.

**Comment by arshiamasih** [comment]
birds-eye view of FE data flow /state mgmt architecture: https://app.diagrams.net/#G16_J0snUuK5JPhgkyFqq8sheUftC4yoRd

simplified view of a POST/PUT event: 
https://app.diagrams.net/#G1qk71_l0pZf3UaHxKEwSfEwZFk_wI15jL

**Comment by arshiamasih** [comment]
8/27/20 Pending decision re: how we utilize Context:

1. [see diagram below] **context is the brain.** components just render JSX for every question and selected/entered response. they maintain the list of questions and responses in their own state, dynamically updated when they ask the context for conditional subquestions. Here context is backed by something like a `Map<QuestionId, Map<ResponseId, Array<SubquestionId>>>` ie
for `Question3 { ResponseA -> [Question3a], ResponseB -> [Question3b, Question3f] }`

2. **context is thin.** it does some one-time heavy lifting of the data after initial fetch so that "viewmodels" are created for each component. All conditional subquestions are given to the components as props and, as it was initially modeled, subquestions JSX elements simply ask component state "is my parent question's response the one i should render myself for?" questions have more in their model:
`Question3a = { Parent: Question3, ParentResponseId: ResponseA, ...question data } `

author: @tylerthome 
![image](https://user-images.githubusercontent.com/23245081/91516079-79417b00-e89f-11ea-9692-a6626195ab1f.png)

**Comment by lola3736** [comment]
@tylerthome please review the complexity and points label for accuracy.
