### ISSUE TITLE
List of data needed for HUU/Coordinator/Local Provider/PSY Dashboards

### ISSUE THREAD

**Issue by abbyhipp** [hackforla/HomeUniteUs#259]
### Overview
We need to decide what information will be placed on the various dashboards before we begin designing the UI

### Action Items
List out all potential data needed for the Coordinator, Local Provider and PSY Dashboard along with what information HUU needs to improve the application in the future

How each member uses the data/dashboard
Coordinator: 
To keep track of workflow

Local Provider:
Funding/Marketing
To understand where Coordinators need help or additional resources

PSY (National Provider):
Funding/Marketing
Mentoring of various Local Providers

HUU:
To make out application better over time
Funding

### Resources/Instructions
Please write down any ideas you have about what data we may want to show on the various dashboards in the comments below. We will consolidate all these items after everyone has written down their comments.
[Everything has been added to the attached excel sheet](
https://docs.google.com/spreadsheets/d/1ryJNGB9KWl33asAR7-Gg604N4w8n70VfxPAeoNYxIo0/edit#gid=0)

**Comment by KarlenS** [comment]
Demographic data (age, gender, race, ethnicity, etc.) might be potentially useful for local providers to identify if there are any subgroups that are disproportionally successful/unsuccessful in the program. Can use this for targeted improvements to their onboarding process or hunt down any existing biases in the program.

**Comment by juliaa423** [comment]
**Coordinator dashboard**
- status of guest and host applications 
- to-do items with reminders for dependencies in workflow (in relation to guest and host)
- calendar of meetings
- FAQs/important documents (ex. drafting a contract)
- transition planning

**Local provider:** 
- case tracker - last correspondence with coordinators or what application stage they are in 
- marketing campaigns
- funding allocation
- FAQs/training material
- guest and host transition progress 

**PSY:** 
- similar to local provider listed above but track progress for local providers rather than coordinators 
- training materials
- funding updates

**Comment by abbyhipp** [comment]
From Calendaring: Successful and not Successful meeting types

**Comment by abbyhipp** [comment]
Geographical data of hosts houses so LP and PSY know where to market it, people that drop off the program and when, length of time for guest to match with a host and when/if guests leave the program, length of time from matching with host to being housed and when/if guests leave the program, progress bar with estimated amount of time(?), progress bar,

**Comment by abbyhipp** [comment]
This has been shifted to the Icebox to be reviewed again on 3/20/2021. We will continue to update this ticket as we learn more about the various data we will need.

**Comment by kpoints** [comment]
Merging these action items with [#329 ](https://github.com/hackforla/HomeUniteUs/issues/329) as they overlap user stories for dashboard.
