### ISSUE TITLE
Host review screen

### ISSUE THREAD

**Issue by abbyhipp** [hackforla/HomeUniteUs#302]
### Overview
As a guest I want to be able to see the hosts profiles I matched with and pick the one I want to be matched with

### Action Items
- [ ] Product
   - [ ] Gather requirements 
      - [ ] Hosts names will be a hyperlink that leads to their profile
      - [ ] Ability to select a smaller group of hosts to review or hide hosts that are a definite no
      - [ ] Button next to hosts names guest will use to indicate their host choice
    - [ ] Discuss with Designers  
- [ ] UI/UX
   - [ ] Create host review screen
- [ ] Development   
   - [ ] Define subtasks (Either in this issue or separate issues if there are multiple and link to this issue)

**Comment by JRHutson** [comment]
Guests need the ability to add hosts to a short-list to make it easier to review and compare.

**Comment by JRHutson** [comment]
If a host that a guest was matched with is removed from the pool, they should get a notification that "2 Hosts from your list are no longer available".
Should not specify which hosts or why to avoid gossip and swirl.
List should be refreshed so that guest is only seeing available hosts at any point.

**Comment by lasryariel** [comment]
duplicate with #617
