### ISSUE TITLE
Pin the table headers to the view in admin view guest matches

### ISSUE THREAD

**Issue by c-fuchs** [hackforla/HomeUniteUs#53]
### Overview
We need to pin in the row of column labels and table/section label so that they stay in view when the user scrolls.

### Action Items
Pin the table label (e.g. "Matched" "Unmatched" "Declined") and column labels (e.g. address, host type, number of guests) to the view
When the user reaches the bottom of that section, that section label should stop scrolling

### Resources/Instructions
[Link to site](http://nonprofitnetworks.com/hosthome/)
screenshot of current section header rows
![image](https://user-images.githubusercontent.com/24849648/73907090-e802ac80-4859-11ea-8477-0ac7b29e8de7.png)
![image](https://user-images.githubusercontent.com/24849648/73907120-04064e00-485a-11ea-9304-ac813ea3d9aa.png)

**Comment by tylerthome** [comment]
This issue pertains to styling of a screen only relevant to the proof-of-concept for Home Unite Us. It was never completed because the POC demo was deemed presentable and demonstrated to stakeholders. If a similar screen will be developed for the Adminstrator/Case Worker it should be formally specified for the MVP iteration

This issue, as written, is obsolete and I recommend closing.
