### ISSUE TITLE
Can't run API test in GitHub Actions

### ISSUE THREAD

**Issue by paulespinosa** [hackforla/HomeUniteUs#576]
### Overview
The API tests fail when run in a GitHub Action.

### Action Items

- [x] Identify the cause of the errors
- [ ] Design and implement a fix that does not involve adding environment variables to GitHub Environments or Secrets

### Resources/Instructions
GitHub workflows do not have AWS credentials or any other environment variables found in the `.env` file. Try running the tests without a `.env` on your local machine to check for test failures.

An example of the test failures is shown in [Create build-deploy-ec2.yml](https://github.com/hackforla/HomeUniteUs/actions/runs/5687521013/job/15416010294)

```
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.3.1, pluggy-1.2.0
cachedir: .tox/py3/.pytest_cache
Using --randomly-seed=587783261
rootdir: /home/runner/work/HomeUniteUs/HomeUniteUs/api
plugins: cov-4.0.0, randomly-3.12.0
collected 17 items

openapi_server/test/test_configs.py ...                                  [ 17%]
openapi_server/test/test_service_provider_controller.py FFFFF            [ 47%]
openapi_server/test/test_service_provider_repository.py .........        [100%]

=================================== FAILURES ===================================
________ TestServiceProviderController.test_get_service_provider_by_id _________

self = <openapi_server.test.test_service_provider_controller.TestServiceProviderController testMethod=test_get_service_provider_by_id>
result = <TestCaseFunction test_get_service_provider_by_id>

    def __call__(self, result=None):
        """
        Does the required setup, doing it here
        means you don't have to call super.setUp
        in subclasses.
        """
        try:
>           self._pre_setup()

.tox/py3/lib/python3.10/site-packages/flask_testing/utils.py:136: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.tox/py3/lib/python3.10/site-packages/flask_testing/utils.py:149: in _pre_setup
    self.app = self.create_app()
openapi_server/test/__init__.py:38: in create_app
    app.add_api('openapi.yaml', pythonic_params=True)
.tox/py3/lib/python3.10/site-packages/connexion/apps/flask_app.py:72: in add_api
    api = super().add_api(specification, **kwargs)
.tox/py3/lib/python3.10/site-packages/connexion/apps/abstract.py:149: in add_api
    api = self.api_cls(specification,
.tox/py3/lib/python3.10/site-packages/connexion/apis/abstract.py:119: in __init__
    self.add_paths()
.tox/py3/lib/python3.10/site-packages/connexion/apis/abstract.py:232: in add_paths
    self._handle_add_operation_error(path, method, sys.exc_info())
.tox/py3/lib/python3.10/site-packages/connexion/apis/abstract.py:244: in _handle_add_operation_error
    raise value.with_traceback(traceback)
.tox/py3/lib/python3.10/site-packages/connexion/apis/abstract.py:222: in add_paths
    self.add_operation(path, method)
.tox/py3/lib/python3.10/site-packages/connexion/apis/abstract.py:175: in add_operation
    operation = make_operation(
.tox/py3/lib/python3.10/site-packages/connexion/operations/__init__.py:16: in make_operation
    return spec.operation_cls.from_spec(spec, *args, **kwargs)
.tox/py3/lib/python3.10/site-packages/connexion/operations/openapi.py:133: in from_spec
    return cls(
.tox/py3/lib/python3.10/site-packages/connexion/operations/openapi.py:80: in __init__
    super().__init__(
.tox/py3/lib/python3.10/site-packages/connexion/operations/abstract.py:101: in __init__
    self._resolution = resolver.resolve(self)
.tox/py3/lib/python3.10/site-packages/connexion/resolver.py:47: in resolve
    return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
.tox/py3/lib/python3.10/site-packages/connexion/resolver.py:68: in resolve_function_from_operation_id
    return self.function_resolver(operation_id)
.tox/py3/lib/python3.10/site-packages/connexion/utils.py:116: in get_function_from_name
    module = importlib.import_module(module_name)
/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
openapi_server/controllers/users_controller.py:5: in <module>
    from openapi_server.controllers.auth_controller import get_token_auth_header
openapi_server/controllers/auth_controller.py:37: in <module>
    userClient = boto3.client('cognito-idp', region_name=COGNITO_REGION, aws_access_key_id = COGNITO_ACCESS_ID, aws_secret_access_key = COGNITO_ACCESS_KEY)
.tox/py3/lib/python3.10/site-packages/boto3/__init__.py:92: in client
    return _get_default_session().client(*args, **kwargs)
.tox/py3/lib/python3.10/site-packages/boto3/session.py:299: in client
    return self._session.create_client(
.tox/py3/lib/python3.10/site-packages/botocore/session.py:948: in create_client
    client = client_creator.create_client(
.tox/py3/lib/python3.10/site-packages/botocore/client.py:123: in create_client
    client_args = self._get_client_args(
.tox/py3/lib/python3.10/site-packages/botocore/client.py:466: in _get_client_args
    return args_creator.get_client_args(
.tox/py3/lib/python3.10/site-packages/botocore/args.py:87: in get_client_args
    final_args = self.compute_client_args(
.tox/py3/lib/python3.10/site-packages/botocore/args.py:183: in compute_client_args
    endpoint_config = self._compute_endpoint_config(
.tox/py3/lib/python3.10/site-packages/botocore/args.py:278: in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
.tox/py3/lib/python3.10/site-packages/botocore/args.py:381: in _resolve_endpoint
    return endpoint_bridge.resolve(
.tox/py3/lib/python3.10/site-packages/botocore/client.py:566: in resolve
    resolved = self.endpoint_resolver.construct_endpoint(
.tox/py3/lib/python3.10/site-packages/botocore/regions.py:205: in construct_endpoint
    result = self._endpoint_for_partition(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <botocore.regions.EndpointResolver object at 0x7f00e695e140>
partition = OrderedDict([('defaults', OrderedDict([('hostname', '{service}.{region}.{dnsSuffix}'), ('protocols', ['https']), ('sig...ict([('variants', [OrderedDict([('hostname', 'xray-fips.us-west-2.amazonaws.com'), ('tags', ['fips'])])])]))]))]))]))])
service_name = 'cognito-idp', region_name = None, use_dualstack_endpoint = None
use_fips_endpoint = None, force_partition = False

    def _endpoint_for_partition(
        self,
        partition,
        service_name,
        region_name,
        use_dualstack_endpoint,
        use_fips_endpoint,
        force_partition=False,
    ):
        partition_name = partition["partition"]
        if (
            use_dualstack_endpoint
            and partition_name in self._UNSUPPORTED_DUALSTACK_PARTITIONS
        ):
            error_msg = (
                "Dualstack endpoints are currently not supported"
                " for %s partition" % partition_name
            )
            raise EndpointVariantError(tags=['dualstack'], error_msg=error_msg)
    
        # Get the service from the partition, or an empty template.
        service_data = partition['services'].get(
            service_name, DEFAULT_SERVICE_DATA
        )
        # Use the partition endpoint if no region is supplied.
        if region_name is None:
            if 'partitionEndpoint' in service_data:
                region_name = service_data['partitionEndpoint']
            else:
>               raise NoRegionError()
E               botocore.exceptions.NoRegionError: You must specify a region.

.tox/py3/lib/python3.10/site-packages/botocore/regions.py:253: NoRegionError
```

**Comment by Joshua-Douglas** [comment]
A project plan for this issue is underway. 

We need to restructure the project to lazy-load our `boto3` client as needed, instead of using the import time initialization. Our current configuration system relies heavily on import-time configurations. We will need to change this behavior in order to properly implement #577 so I am planning on extending the application configuration system to support environment-specific configurations of the application. 

Using this approach the `boto3` client will be created using real AWS credentials for `PRODUCTION` and `STAGING` and `DEVELOPMENT` environments, but the client will be disabled for `TESTING` environments. 

In the future we will need to mock the boto client, which can be done using the moto client, but for now it is sufficient to throw an `NotImplementedException` if the testing app tries to access the boto client. 

I'll include a draft project plan down below. My plan is to update the PP as my general solution and implementation progresses.

**Comment by Joshua-Douglas** [comment]
# Overview

The API test cases fail when run from the GitHub test runner, because our testing workflow does not provide an `.env` file containing the project secrets.

Our test cases do not currently require access to any secrets. Restructure the project to remove the unintentional use of secrets from the test project.

## Research

### What is the exact error we are encountering?

If you remove the AWS Congnito secrets from your `.env` file and run the tests locally an error is thrown during the import of `auth_controller.py` within the call to `boto3.client`.

```py
openapi_server\controllers\users_controller.py:5: in <module>
    from openapi_server.controllers.auth_controller import get_token_auth_header
openapi_server\controllers\auth_controller.py:37: in <module>
    userClient = boto3.client('cognito-idp', region_name=COGNITO_REGION, aws_access_key_id = COGNITO_ACCESS_ID, aws_secret_access_key = COGNITO_ACCESS_KEY)
```

Our test cases do not currently use authentication, but the authentication py files do get imported. Importing `auth_controller.py` currently requires valid credentials to work - even if you do not use any of the imported functionality.

### How do we currently configure the API app?

Since we are using `connexion` we have two application classes - a [connexion.apps.flask_app.FlaskApp](https://connexion.readthedocs.io/en/2.13.1/autoapi/connexion/apps/flask_app/index.html#connexion.apps.flask_app.FlaskApp) and a [flask.Flask](https://flask.palletsprojects.com/en/2.3.x/api/#flask.Flask) app.

The `connexion` `FlaskApp` is a wrapper around the `Flask` application class. Each class has their own specific configuration options.

We currently configure both application classes using this factory method within `opeanapi_server.__main__.py`.

```py
def create_app():
    '''
    Creates a configured application that is ready to be run.

    The application is configured from external environment variables stored
    in either a local `.env` in a development environment or from environment
    variables that are configured prior to running the application.

    This function is made available at the module level so that it can
    be loaded by a WSGI server in a production-like environment with
    `openapi_server.__main__:create_app()`.
    '''

    # `connexion.App` is aliased to `connexion.FlaskApp` (as of connexion v2.13.1)
    # which is the connexion layer built on top of Flask. So we think of it as
    # the connexion application.
    connexion_app = connexion.App(__name__)
    api_spec_path = connexion_app.get_root_path() / Path('./openapi/openapi.yaml')
    parsed_specs = get_bundled_specs(api_spec_path)

    parsed_specs['info']['version'] = get_version()

    connexion_app.add_api(parsed_specs, pythonic_params=True)
    connexion_app.add_error_handler(AuthError, handle_auth_error)

    ENV_FILE = find_dotenv()
    if ENV_FILE:
        load_dotenv(ENV_FILE)
    SECRET_KEY = env.get("SECRET_KEY")
    env_config_profile = get_key(find_dotenv(), "CONFIG_PROFILE")

    # The underlying instance of Flask is stored in `connexion_app.app`.
    # This is an instance of `flask.Flask`.
    flask_app = connexion_app.app
    flask_app.json_encoder = encoder.JSONEncoder
    flask_app.secret_key = SECRET_KEY

    # Below, the Flask configuration handler is loaded with the
    # application configuration settings
    flask_app.config.from_object(compile_config(env_config_profile))

    return connexion_app
```

The `FlaskApp` and `Flask` applications are configured separately. Much of the configuration is hard coded using these statements, but we do have some infrastructure to allow additional configuration parameters to be specified using a `.env` file.

The `load_dotenv` method loads all of the variables available within the `.env` file as environment variables. After this call, all of the key-value pairs available within the `.env` file are available using `os.environ("Key")` (Note: by default `load_dotenv` will not override existing environment variable values).

We use some of these env variables to explicitly set some configuration properties of our flask app, and we use a custom configuration system to set the rest - with `custom_config`.

### How does our custom configuration system work?

Our custom configuration system's entrypoint is `api.configs.configs.py::compile_configs.`. This method returns a configuration class that is passed to `FlaskApp.configuration.from_object`. The `from_object` method will iterate over the uppercase attributes on the object and add them to the configuration as key-value pairs.

The flask docs provide [a warning](https://flask.palletsprojects.com/en/2.3.x/api/#flask.Config.from_object) with the `from_object` method:

>You should not use this function to load the actual configuration but rather configuration defaults. The actual config should be loaded with from_pyfile() and ideally from a location not within the package because the package might be installed system wide.

```py
class Config():
    HOST = '0.0.0.0'
    PORT = 8080
    DEBUG = True
    USE_RELOADER = True

def compile_config(profile: str, mod: str = 'configs.personal', clazz: str = 'PersonalConfig') -> Config:
    config = Config()

    if profile == 'personal':
        try:
            personal_mod = importlib.import_module(mod)
            personal_config = getattr(personal_mod, clazz)
            config = personal_config
        except ModuleNotFoundError:
            raise
    
    # handle other profiles here

    return config
```

This method will return the default to the `config` if an unrecognized profile is provided.

To use the `personal` profile you need to do the following:

1) Specify the profile within your `.env` file (`CONFIG_PROFILE=personal`)
2) Add a python file to the `configs` package, with a name matching the `mod` param
3) Within your new python file, add a class with a name matching the `clazz` param
4) If `mod != configs.personal.py` or `clazz != PersonalConfig` then you will need to update the implementation of the existing `create_app` method to use the custom configuration (or add a new factory method)

### How do we configure the API database

The database is configured at just before the apps are created during the module import of `openapi_server.__main__.py`.

If a `DATABASE_URL` env variable is specified then the `DataAccessLayer` will use it to create a `SQLAlchemy` database engine. Otherwise, the default value of `"sqlite:///./homeuniteus.db"` is used. (Note: You cannot currently specify the `DATABASE_URL` within the `.env` file since the database is initialized before the factory method's call to `load_dotenv`).

```py
#__main__.py
from openapi_server.models.database import DataAccessLayer
DataAccessLayer.db_init()
```

```py
#database.py
DATABASE_URL = env.get('DATABASE_URL')
class DataAccessLayer:
    _engine: Engine = None
    
    # temporary local sqlite DB, replace with conn str for postgres container port for real e2e
    _conn_string: str = DATABASE_URL if DATABASE_URL else "sqlite:///./homeuniteus.db"

    @classmethod
    def db_init(cls, conn_string=None):
        Base.metadata.create_all(bind=cls.get_engine(conn_string))
    
    # other code
    
    @classmethod
    def get_engine(cls, conn_string=None) -> Engine:
        if cls._engine == None:
            cls._engine = create_engine(conn_string or cls._conn_string, echo=True, future=True)
        return cls._engine
```

### What application configurations should we be able to support

Four types of configurations will likely be enough to serve all of our needs:

#### Production flask application

This the configuration for the real application that users will access, from `homeunite.us`. It should use a production grade WSGI server, and should have any and all mocking removed.

The production application configuration will require the strictest configuration validation, to ensure our deployed application is working as expected.

#### Staging flask application

The staging flask app is intended for internal use only, and will be hosted at `dev.homeunite.us`. The configuration should nearly mirror the production configuration. There may be some slight variations (such as a different flask `SECRET_KEY` to keep sessions distinct), but we will still need to apply strict configuration validation here.

#### Development flask application

The development flask app is intended to run on a developer's local machine. The development backend will need to work with the frontend app, and the developer should be able to add test data to user database without the risk of polluting the production API's data.

The development app currently runs with a non-production grade WSGI server that allows for easy debugging of the API code. Mocking within the development application is allowed, especially if the mocking limits the distribution of sensitive API service keys, minimizes the risk of passing external API call limits, or minimizes the risk of polluting the production database.

Ideally developers would be able to run a version of the application without any secrets. If this is done, then careful attention would be needed to ensure that all mocked services are stripped from the production application's configuration.

#### Development Testing flask application

The development testing application should be configured very similarly to the development application. More aggressive mocking can be used here to restrict the use of networking resources, to allow targeted unit tests instead of relying on I/O bound integration tests. I/O bound methods (e.g. network calls, database file storage, etc.) can make the clean setup & teardown of tests difficult to achieve, while also slowing down the entire test suite.

Our current testing application does not run any WSGI server at all. Instead we use the [WSGI Test Client](https://werkzeug.palletsprojects.com/en/2.2.x/test/) to simulate requests to the connection/flask applications. An in-memory database is also used, to prevent disk writes. There is currently no option to mock the authentictation system, so real API calls to the AWS Cognito service are required. This feature is expected to be added in issue [#577](https://github.com/hackforla/HomeUniteUs/issues/577).

#### Release Testing flask application

It could also be beneficial to include a testing application that strips all mocking, and performs tests using real databases and API network calls. These tests would verify that the application mocking is not hiding bugs covered by our test cases. Running this test suite would be slower and would risk hitting API limits, etc. We could compensate for this risk by running the test cases when release testing is required. For example, these tests could be configured to run as a post-build step during the staging environment deployment.

### How does flask recommend configuring a complex project?

Flask has a [configuration guide](https://flask.palletsprojects.com/en/2.3.x/config/) that has three strong recommendations that we will follow in this issue:

1. Use factory method to create the app. The factory should accept a configuration parameter.
2. Do not write code that needs the configuration at import time
3. Load configuration very early on (before creating the application class)

**We are currently violating the second rule. We do configure at import time, and this is breaking our test project.**

The guide discusses the need for distinct development and production configurations. A common pattern is to store sensible default configurations in version control, and then use environment variables to swap between configuration types.

```py

```

### List the current configuration options we use

### How do we run the production API app?

## General

We will update our current configuration system to:

* Introduce an environmental variable, `HUU_ENV` that can be used to switch between application environments.
  * Currently the only way to switch between environments is to update the source code, but the environment should be configurable from the terminal.
  * We will default to the `DevelopmentConfig` if no configuration is selected.
* Update the current configuration system to avoid import-time configurations. We will use the application factory pattern instead, so configurations are not loaded until the application is created.
  * Add `DevelopmentConfig.py`, `StagingConfig.py`, `ProductionConfig.py`, and a `TestConfig.py` class.
  * Each config will descend from our current `Config` class. This parent class will store configuration options that apply to all configurations.
  * (Maybe my factory method should accept a dictionary too to make passing test configs easy?)
* Extend the current configuration system to declare development, production, and test configurations. All secrets will be loaded from the environment, but non-secret configurations will store reasonable defaults in code.
* Update the botoClient initialization code to lazy load the client.
* (Optional) Introduce a release testing project configuration. This will run the application using real HTTP requests instead of simulated requests.

Let's set the ServerName.

## Implementation Questions

### Show an app factory method that allows us to select configuration from the terminal

This is still in draft. My plan is to use the approach provided by the flask docs, but modified to work with connexion.

```py
# default to the development configuration
env_config = os.getenv("HUU_ENV", "config.DevelopmentConfig")
app.config.from_object(env_config)

def create_app(test_config=None):
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY='dev',
        DATABASE=os.path.join(app.instance_path, 'flaskr.sqlite'),
    )

    if test_config is None:
        # load the instance config, if it exists, when not testing
        app.config.from_pyfile('config.py', silent=True)
    else:
        # load the test config if passed in
        app.config.from_mapping(test_config)

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    return app
```

### Show the different configurations

The parent Config class includes validation logic.

```py
# huuappenv.py
class HUUAppEnv(Enum):
    DEVELOPMENT = 'development'
    STAGING = 'staging'
    PRODUCTION = 'production'
    TEST_DEBUG = 'test_debug'
    TEST_RELEASE = 'test_release'
```

```py
# config.py, development_config.py, production_config.py, staging_config.py 
from dataclasses import dataclass, fields

@dataclass(frozen=True)
class Config:
    DEBUG: bool
    HOST: str
    PORT: int = 8080
    USE_RELOADER: bool
    SECRET_KEY: str
    ROOT_URL: str

    def __post_init__(self):
        for field in fields(self):
            env_value = os.environ.get(field.name)
            if env_value is not None:
                expected_type = type(getattr(self, field.name))
                cast_value = expected_type(env_value)
                object.__setattr__(self, field.name, cast_value)
        self.validate()

    def validate(self):
        for field in fields(self):
            if getattr(self, field.name) is None:
                raise ValueError(f"Configuration option {field.name} is None.\
                                 All configuration values must be specified \
                                 to properly start the application. Secrets \
                                 should be specified as environment variables, \
                                 and configuration variables should be specified \
                                 in code.")

@dataclass(frozen=True)
class DevelopmentConfig(Config):
    DEBUG: bool = True
    HOST: str = "0.0.0.0"
    USE_RELOADER: bool = True
    SECRET_KEY: str = "unsecurekey"

@dataclass(frozen=True)
class ProductionConfig(Config):
    COGNITO_CLIENT_ID: str
    COGNITO_CLIENT_SECRET: str
    COGNITO_REGION: str
    COGNITO_REDIRECT_URI: str
    COGNITO_USER_POOL_ID: str
    COGNITO_ACCESS_ID: str 
    COGNITO_ACCESS_KEY: str

    def validate(self):
        super().validate()
        self.validate_secret_key(self.SECRET_KEY)

    def validate_secret_key(self, key):
        """
        Validates a secret key by checking multiple conditions:
        1) Minimum 16 characters
        2) At least one uppercase letter
        3) At least one lowercase letter
        4) At least one digit
        """
        errors = []
        if len(key) < 16:
            errors.append("The key must be at least 16 characters long.")

        if not re.search("[a-z]", key):
            errors.append("The key must contain at least one lowercase letter.")

        if not re.search("[A-Z]", key):
            errors.append("The key must contain at least one uppercase letter.")

        if not re.search("[0-9]", key):
            errors.append("The key must contain at least one digit.")

        if len(errors) > 0:
            raise ValueError(f"Production secret key is not strong enough.\
                             {''.join(errors)}")

@dataclass(frozen=True)
class StagingConfig(Config):
    pass
```

### Show how to lazy load a boto3 client

We can achieve this by adding an app class that uses the application configuration to instantiate the correct AWS identity provider client.

```py
# huuapy.py 

from connexion.apps.flask_app import FlaskApp
from flask import Flask
from enum import Enum

class HUUAppEnv(Enum):
    DEVELOPMENT = 'development'
    STAGING = 'staging'
    PRODUCTION = 'production'
    TEST_DEBUG = 'test_debug'
    TEST_RELEASE = 'test_release'

class HUUApp(FlaskApp):
    def __init__(self):
        super().__init__()
        self.app: Flask
        self._boto_client = None

    @property 
    def environment(self) -> str:
        return self.app.config["HUU_ENV"]
    
    @property 
    def is_debug_app(self) -> bool:
        return self.environment in (
            HUUAppEnv.DEVELOPMENT,
            HUUAppEnv.TEST_DEBUG
        )

    @property
    def boto_client(self):
        if self._boto_client:
            return self._boto_client
        
        if self.environment == HUUAppEnv.TEST_DEBUG:
            raise NotImplementedError("Debug mode test cases should not use a \
                                      real boto_client, but client mocking has \
                                      been implemented yet. This feature is planned \
                                      in Issue #577")
        import boto3
        self._boto_client = boto3.client('cognito-idp', 
                                         region_name=self.app.config["COGNITO_REGION"], 
                                         aws_access_key_id=self.app.config["COGNITO_ACCESS_ID"],
                                         aws_secret_access_key=self.app.config["COGNITO_ACCESS_KEY"]
                                         )
        return self._boto_client
```

### Do we need to set the flask_app JSON encoder?

We are using a custom version of `connexion.app.flask_app.FlaskJSONEncoder`. Our custom version simply sets `include_nulls` to `False`.

`FlaskJSONEncoder` uses `Flask.json.JSONEncoder`. This encoder is deprecated and set to be removed in `Flask` v2.3.

`connexion` already sets the `FlaskJSONEncoder` within the internal `FlaskApp.create_app()` factory method, so we do not need to set the json encoder if we do not need to override it.

```py
class FlaskApp(AbstractApp):
    def create_app(self):
        app = flask.Flask(self.import_name, **self.server_args)
        app.json_encoder = FlaskJSONEncoder
        app.url_map.converters['float'] = NumberConverter
        app.url_map.converters['int'] = IntegerConverter
        return app
```

**Comment by paulespinosa** [comment]
@Joshua-Douglas good write up. @ju1es has created separate issues to implement a config system. The implementation of the proposed configuration implementation can close #530 too.

Create Config System #522  - This is where it started and is closed now
Create Config System For Configs at Runtime #530 - Open seem most related to your write up on the config system.
Create Config System For Credentials #529 - Open

**Comment by paulespinosa** [comment]
We'll have a specific staging environment that's distinct from what we have/will have at `dev.homeunite.us`.

In the write-up https://github.com/hackforla/HomeUniteUs/issues/576#issuecomment-1712418608, I called it "deployed test dev" for lack of a better word or description.

I included some information about the `dotenv` command-line tool. It is currently used to load the `DATABASE_URL` variable that is stored in the `.env` file as an environment variable before running the API.

**Comment by Joshua-Douglas** [comment]
Thanks for adding that section @paulespinosa! Design is still in draft form, but I should be done (with an implementation for the most important parts) by Monday.

I'm hoping to close #522 & #530 with this issue since these are closely related. It should partially address #529, but not fully since I won't touch the front end app in this issue.

**Comment by Joshua-Douglas** [comment]
Hey @paulespinosa - I thought about your comments a bit more and decided that it would be much clearer if we moved the research to #530. Thanks for the heads up on that issue.

**Comment by Joshua-Douglas** [comment]
Moved to ice box since this issue depends on #530.

**Comment by paulespinosa** [comment]
@Joshua-Douglas Sounds good! Thank you.
