### ISSUE TITLE
Decide where to store default and actual images and implement

### ISSUE THREAD

**Issue by c-fuchs** [hackforla/HomeUniteUs#58]
### Overview
We need to Replace Fill Murray with default or actual images for guest and host profiles so that the guest and host can show images on their profiles.

### Dependencies
Issue #56   
Issue #39 

### Action Items
- [ ] Decide where and how to store default and actual images
- [ ] Update data schema to include image_face and images_other (1 picture will have to be primary, the one of the face. All other images will go into secondary display).
- [ ] Document decision in this issue

### Resources/Instructions
[Guest CSV](https://docs.google.com/spreadsheets/d/19jHgjezTa3uI91Tj2sHFcYVu65QpdfHBOrOhDB5iUIo/edit#gid=379445183)
[Host CSV](https://docs.google.com/spreadsheets/d/10FZay2EAA8yfZwzb4POt-_P-gJpQGE4IjddBJiZMssE/edit#gid=127843313)

**Comment by c-fuchs** [comment]
As decided on 2/15 call, placeholder images will be saved in the google drive, in Product Design docs--> Design Images-->Placeholder images

**Comment by tylerthome** [comment]
The application server will store and retrieve image data from the DBMS. The HomeUniteUs database will not treat image data significantly differently from other data types. A guest's profile image will be stored within the guest's master record, or in a record related by foreign key.

Some DBMS may provide an API directly supporting upload/download of files (such as MongoDB's GridFS), others may require custom code to be written for the serialization and parsing between raw bytes and MIME payloads. The HomeUniteUs application will wrap this implementation into the data access layer, so that migrating to a new DBMS will not create a large development burden.

**Comment by tylerthome** [comment]
@HassenH1 has set up the webservice to store images in GridFS for the Host's Home images in PR #207  providing the proof of concept for how images can be stored and linked to accounts going forward. Recommend closing this issue

**Comment by lola3736** [comment]
@tylerthome please review points and complexity label for accuracy.
