### ISSUE TITLE
App: Node 16.x reaching end-of-life support

### ISSUE THREAD

**Issue by paulespinosa** [hackforla/HomeUniteUs#588]
### Overview

Node 16.x is reaching End-Of-Life support on 2023-09-11. 

https://github.com/nodejs/release#release-schedule
https://nodejs.org/en/blog/announcements/nodejs16-eol 

### Action Items

- [ ] Update the app, packages, tools to the next version of Node (18.x for LTS or 20.x for current)
- [ ] Update documentation
- [ ] Update GitHub Actions

**Comment by Joshua-Douglas** [comment]
# Overview

Upgrade the project to use discontinue the use of Node.js v16.x since this version of Node has reached end-of-life support.

## Research

### What is node.js?

> Brief 1-3 sentence summary

### What is the current Long Term Support (LTS) version?

> You can find this on the node.js website

### Should we use the most recent version of Node.js or the LTS version?

> What are the pros and cons of this choice?

### What does is mean when Node.js reaches end-of-life support?

> Why is it important that we upgrade? Think security risk.

### What does 'npm run build' do?

> Hint: We configure this behavior. You can run 'npm run' for a full list.

### How do we specify the Node.js version for our app Docker image?

> What version of node are we specifying? You can find this info by reviewing the Dockerfile & comparing it to the [docs](https://hub.docker.com/_/node/). I recommend you run the docker container and check the version through the terminal to verify your answer. Let me know if you need help doing this.

### How do you enforce a minimum version of node.js?

> I believe this is possible, but I would need to research this myself. If you find a way then that would be great!

### How could upgrading Node.js break our project?

> Hint: New versions of Node may break backwards compatibility

### If upgrading breaks our project, how should we address those breaks?

### How do you install a new version of node.js?

### How do you upgrade the version of a dependency listed in package.json?

### What is a GitHub workflow?

> How could upgrading Node.js break our workflows?

## General Solution Plan

We'll put this together once your research is complete. We need to make sure the local build and docker build continues to work.

**Comment by Joshua-Douglas** [comment]
Hey @mira-kine,
 
An initial project plan is ready for this issue. Please submit your answers and reassign me once it is ready for review. Each response can be as brief as a few words / sentences. I just want to make sure we are on the page!

My comments are included as

> quoted text

Please don't remove those section. I'll remove them as I review your responses.

**Comment by Joshua-Douglas** [comment]
Great PP @mira-kine! I added my minor comments 

> as quotes 

and added a general solution plan along with a snippet showing how to update the workflows. You should be good to open a branch now, unless I've left anything our or if you have any questions.

Our `app` docker container already uses v18.18.0 so I don't think there will be any issues building the project once you upgrade! The best way to be sure of this, though, is to run the test cases and do some manual testing.

**Comment by Joshua-Douglas** [comment]
Hey @mira-kine, 

So sorry I forgot to save my last edits 🤦. The PP is updated and I think you are good to open a branch! If you need any help with anything just let me know!

**Comment by mira-kine** [comment]
Hi @Joshua-Douglas,  I am finally back and active. The LTS version of node is now 20.x (as of October 18), with its active support ending in 11 months and security support ending in 2 years [according to this schedule](https://endoflife.date/nodejs). I will update to 20.x instead, with the same solution plan. Thank you!
